### ISSUE TITLE
Patching the same directory with diff

### ISSUE THREAD

**Issue by MsMaciek123** [sisong/hsynz#10]
Will be setting oldPath and outNewPath to the same path supported? Currently it throws an error:
not support oldPath outNewPath same path "directory" ERROR!
It is kinda needed, because currently it requires double space to be able to patch directory.

**Comment by sisong** [comment]
now, not support oldPath outNewPath same path.      

Because I haven't figured out how to deal with this situation clearly.       
The most critical problem: it is not possible to safely and securely delete files in oldDir that are not in newDir.

**Comment by dungeon2567** [comment]
Why is it not possible to safely delete this files?
Do you mean they are not part of the directory anymore?

**Comment by sisong** [comment]
When using hdiffz, both oldDir and newDir are inputed, then it is possible to know: from oldDir to newDir, which files remain unchanged, which files have been modified, which files have been added, which files have been deleted, and which files have been renamed.   
   
on the other hand, only input newDir to hsync_make, while the oldDir inputed to hsynz can by default only be seen as reference data: there may be old version data, program or system generated data, user saved or edited data, and other data that may be relevant to the new version(can reduce download data).
