### ISSUE TITLE
diffi 生成的是确实的数据块集合吗？

### ISSUE THREAD

**Issue by RPG3D** [sisong/hsynz#18]
感觉实际使用流程应该是下载远程index，对比本地OldData，生成diffinfo，然后再去下载，有没有一些指引呢

**Comment by sisong** [comment]
客户端需要4个步骤： 下载hsyni文件，diff计算出需要下载的块信息，下载块，和已有old数据合并得到new数据。   
具体到命令行，可以一次执行完所有4个步骤得到最终的new数据，也可以每个步骤单独执行。   
建议阅读中文版的说明，命令行的使用有解释。

**Comment by meilaopo** [comment]
没看明白这行 【同步打补丁  : [options] oldPath [-dl#hsyni_file_url] hsyni_file hsynz_file_url outNewPath [-diffi#cacheTempFile] 】
我想用前面步骤生成cacheTempFile去下载所有缺失的数据（结果应该是difffile）。等所有缺失数据全部下载完成再执行patch步骤
该怎么填写参数呢

**Comment by meilaopo** [comment]
这一步把diff信息和下载合在一起了【创建本地补丁: [options] oldPath hsyni_file hsynz_file_url -diff#diffFile】
我是想把计算下载内容和下载完全分开（方便一次把下载任务交给专用下载工具去下载）

**Comment by RPG3D** [comment]
预计客户端应该是先检查（下载）最新的index文件，即readme的【下载文件】
然后计算下载大小，即 【查询同步信息】，此时可以在界面告知下载大小；保存cacheTempFile
然后下载更新包，就是 【创建本地补丁】
最后执行【本地打补丁】

参数diffi#cacheTempFile可以在哪些阶段使用呢

**Comment by Thur4day** [comment]
> 预计客户端应该是先检查（下载）最新的index文件，即readme的【下载文件】 然后计算下载大小，即 【查询同步信息】，此时可以在界面告知下载大小；保存cacheTempFile 然后下载更新包，就是 【创建本地补丁】 最后执行【本地打补丁】
> 
> 参数cacheTempFile可以在哪些阶段使用呢

请教一下，客户端的hsynz.IRangeDownloader实现能给讲解一下吗？
如何实现readDownloadedData方法，写入到本地补丁文件？

**Comment by sisong** [comment]
@Thur4day 
readDownloadedData方法，并不负责写本地补丁文件； 这个函数的任务是将你自己下载到的块的数据通过一个缓冲区传递给native层；  native层会根据任务要求完成patch或保存补丁的任务。
