### ISSUE TITLE
开启continue时需要业务层自行处理diff文件兼容文件吗

### ISSUE THREAD

**Issue by meilaopo** [sisong/hsynz#19]
客户端diff到一半关闭进程，然后cdn上文件变化了，下次继续diff，hsynz内部有相关校验呢 还是需要业务侧自行处理

**Comment by sisong** [comment]
对于缓存临时文件的continue：   
如果newFile变化了，那.hsyni文件必然需要重新下载，这时缓存的文件也会自动失效，不需额外处理，因为缓存的同步信息中保存了上一次的newFile的校验码。    
如果newFile变化了，但.hsyni文件错误的继续使用了上一次的，这时缓存的文件继续有效，可能得到上一次的newFile(而不是变化后的newFile)或大概率报校验错误(因为从.hsynz文件下载到数据也很可能变了)。  
如果本地oldFile数据变化了,但大小一样，newFile不变，这时缓存的文件继续有效，可能得到正确的newFile或报校验错误(因为old数据变了造成new数据校验失败)。  
如果本地oldFile变了前后大小不一样，newFile不变，这时缓存的文件自动失效，因为缓存的同步信息中保存了上一次的oldFile的大小。  
 （可参见`_TSyncDiffData_readOldPoss`的代码）   

推荐实践：临时文件的文件名中包含old和new的版本号或其他唯一码信息。

**Comment by meilaopo** [comment]
校验hdiff个hsyni是不是对应函数是这个吧 _TSyncDiffData_readOldPoss
校验码是指savedNewDataCheckChecksum ？

**Comment by sisong** [comment]
是的，这个是保存的new数据的强校验值。
