### ISSUE TITLE
hsynz生成的diff比hdiffz明显大很多

### ISSUE THREAD

**Issue by meilaopo** [sisong/hsynz#20]
有2个接近200MB的exe文件
按hdiffz对比差异大约30MB（无压缩参数）
hsynz则170MB+， 参数-s-32k
有什么办法能改进吗

**Comment by sisong** [comment]
不加压缩参数对比无意义，建议都选zstd压缩。   
hsynz在make时，根据数据大小建议选择2k的块大小。     
hsynz的补丁一般都会比hdiffz的大，这是算法原理决定的。

**Comment by meilaopo** [comment]
> 不加压缩参数对比无意义，建议都选zstd压缩。 hsynz在make时，根据数据大小建议选择2k的块大小。 hsynz的补丁一般都会比hdiffz的大，这是算法原理决定的。

hsynz压缩模式对内存是不是很高。hdiffz需要数倍于原文件的内存，hsynz没有详细说明；因为我还用一个近30GB的文件测试压缩模式，需要很久

**Comment by sisong** [comment]
30GB的文件 那块大小应该增大很多，比如256k?具体多少合适需要测试。      
这种大文件，压缩会比较慢，好在只需要make一次，建议稍微调低zstd压缩级别。   
    
hsynz的服务端make，内存复杂度只和块大小、压缩字典大小、并行线程数有关；   
而客户端同步算法内存复杂度只和块大小、压缩字典大小相关。
