### ISSUE TITLE
weak hash还有别的备选方法吗 目前adler64有崩溃问题

### ISSUE THREAD

**Issue by meilaopo** [sisong/hsynz#21]
想换个方法看看是生成的hindex错了还是hash本身的问题

**Comment by meilaopo** [comment]
新旧文本本身是一样的。

<img width="1229" alt="WXWorkCapture_17159164905457" src="https://github.com/sisong/hsynz/assets/59859171/c49456be-3b22-4f51-b9a9-bd3535845d4c">

<img width="1047" alt="WXWorkCapture_17159165098973" src="https://github.com/sisong/hsynz/assets/59859171/0afe0fb6-d5c8-4168-8e71-455302d1437a">

感觉控制模式应该也出错了，但是没有相关日志
<img width="1102" alt="WXWorkCapture_17159165171423" src="https://github.com/sisong/hsynz/assets/59859171/521c94b0-a356-42b5-a3e0-36fbce20e485">

**Comment by meilaopo** [comment]
match_in_old.cpp 249行是不是有些问题，下面nextBlock按照blocksize增加，会导致249行错过end位置？

**Comment by sisong** [comment]
不是hash的问题，猜测应该是某个边界条件没有处理

**Comment by meilaopo** [comment]
测试文件是一个200KB的dll，index不会很大吧？

**Comment by meilaopo** [comment]
[TestPatch.zip](https://github.com/sisong/hsynz/files/15345070/TestPatch.zip)

**Comment by sisong** [comment]
谢谢提交的用例，发现是一个代码逻辑错误，已经修复。    
需要重新编译代码，二进制版本我可能明天编译后上传。
