### ISSUE TITLE
sync_local_diff步骤如何获取进度呢

### ISSUE THREAD

**Issue by meilaopo** [sisong/hsynz#22]
目前主要在分析diffi，下载diff，生成new步骤消耗较多时间，需要展示进度。
我修改了下载代码，广播进度，对于生成new步骤可以在自定义写入函数广播，但是分析diffi步骤不知道如何估算

**Comment by sisong** [comment]
这个过程中，需要计算出下载哪些块(diff)，然后下载这些块，两者可能都比较耗时。   
diff过程为matchNewDataInOld()函数,  其中耗时部分支持多线程并行。单线程时，roll循环总长为oldsize, 多线程时将总长分成了workCount个任务。    
下载过程为writeToNewOrDiff函数,  这个处理简单一些，因为知道需要下载的总长度。

**Comment by meilaopo** [comment]
目前在读取old data步骤广播进度，效果还行
