### ISSUE TITLE
Chunked hsynz output files

### ISSUE THREAD

**Issue by Zeblote** [sisong/hsynz#24]
Hi, it would be useful if the program could write the hsynz output as multiple chunks of some specified size (such as 100MB). Some hosts cannot provide range requests efficiently from arbitrarily large files.

It would also be useful if it can send several http requests in parallel to improve download speed on high latency connections (such as one for each of the split files above). Or does it already do this? If so, can we limit how many concurrent requests it makes?

**Comment by sisong** [comment]
For special I/O datas, it is recommended to call the API directly, which provides streaming interface that can be used to abstract special datas.   
This lib's cmdline hsync_http does not provide parallel downloads, you can add by yourself, such as: initiating an asynchronous multi-threaded download when you know all the blocks that need to be downloaded.
