### ISSUE TITLE
adler_roll.c 422行有崩溃

### ISSUE THREAD

**Issue by meilaopo** [sisong/hsynz#27]

**Comment by meilaopo** [comment]
match_in_old.cpp 261行 >改成>=暂时能缓解

**Comment by meilaopo** [comment]
match_in_old.cpp 261行 >改成>= 能缓解  
data_end应该是最后一个有效数据往后一字节吧？

**Comment by sisong** [comment]
用的是什么版本，最近修复过一次内存访问bug。     
可以把代码前后的都贴上来。

**Comment by meilaopo** [comment]
印象中是一个月前的master代码，clone的hdiffpatch（里面带了libhsynz）
然后合并了前几天一个越界修改https://github.com/sisong/HDiffPatch/commit/6c0c660da984f18588f1b70e9b8d9098cfd872b5

**Comment by sisong** [comment]
更新到最新的版本代码试试。    
如果还有该问题（即使很小概率），是否方便给我你的测试用例?

**Comment by meilaopo** [comment]
暂时没能复现了，可能是先前某些代码误修改了

**Comment by meilaopo** [comment]
debug模式不好触发，release模式概率很高，改用master最新代码后没有复现了
