### ISSUE TITLE
diff出来的info文件怎么在patch阶段利用起来，不要重复分析差异

### ISSUE THREAD

**Issue by meilaopo** [sisong/hsynz#28]
目前主要步骤如下：
1 sync_local_diff(kSyncDiff_Info) 获取下载大小，此步骤会生成info文件;这里为了从读取old时刷新进度没用file2file
2 sync_local_diff_file2file(kSyncDiff_Data)执行下载
3 sync_local_patch() 生产新版文件
该怎么把步骤1的info文件传给步骤2,3避免重复计算呢

**Comment by sisong** [comment]
. `sync_local_diff(kSyncDiff_Info) `
 可以执行diff计算并把结果保存到参数`cacheDiffInfoFile`对应的文件中（假设文件为 diff.tmp）    
. `sync_local_diff_file2file(kSyncDiff_Data)执行下载`    
  不能使用`kSyncDiff_Data`，提示里有注明，该项一般仅用于测试：将需要下载的数据的单独保存为一个文件。    
而应该使用`kSyncDiff_default`, 并且`outDiffFile`参数为上一次调用使用同一个文件(即 diff.tmp)，且`isOutDiffContinue`为true；   
这样函数读取到diff.tmp中的diff计算结果，就可以立即开始下载，并把下载到的数据保存到diff.tmp中。   
. `sync_local_patch() 生产新版文件`    
 该函数的参数`inDiffFile`为上一次调用使用同一个文件(即 diff.tmp)，这样就可以避免重复计算了。

**Comment by RPG3D** [comment]
info和diif是同一个文件，有个文件，下载阶段中断，下次重新执行sync_local_diff(kSyncDiff_Info) ，会不会把之前的下载进度清理了

**Comment by sisong** [comment]
isOutDiffContinue为true 就能保留继续下载。

**Comment by RPG3D** [comment]
> 继续下载应该用 kSyncDiff_default而不是kSyncDiff_Info（没有测试过这样用，映像中是跳过，什么都不做?），isOutDiffContinue为true 就能保留继续下载。

下次继续是在杀进程后重新走123步骤，此时要避免上次步骤2下载一半的diff被此处步骤1获取下载大小时被清理了

**Comment by sisong** [comment]
下载的数据都不会被清除，而且在加载到已有数据后diff计算也会被跳过。

**Comment by meilaopo** [comment]
下载阶段主要在writetonewordiff函数，末尾copy from old把整个旧文件读取了一遍，消耗比较大 在kSyncDiff_Info应该可以计算出需要下载的块以及旧文件中可以复用的块，这里计算主要是干啥呢

**Comment by sisong** [comment]
主要时间可能消耗在： 读取old数据、写入new数据、读取和解压下载到的数据、校验数据；   前两项I/O应该是瓶颈。

**Comment by meilaopo** [comment]
> 主要时间可能消耗在： 读取old数据、写入new数据、读取和解压下载到的数据、校验数据； 前两项I/O应该是瓶颈。

实际下载前会完全读取一次old数据，然后才触发下载

**Comment by sisong** [comment]
是的，第一次会顺序读取整个old数据，确定哪些数据可以被重用；这里第二次会（依据new数据的写入顺序）随机读取那些标记可以重用的old数据。  这两次访问应该很难被合并优化为一次访问。

**Comment by meilaopo** [comment]
下载完diff先不patch，重新执行kSyncDiff_Info 分析获取大小，这里调用hpatch_TFileStreamOutput_open函数打开diff输出文件，会清空上次下载的文件内容

**Comment by sisong** [comment]
你有设置成continue状态吗？

**Comment by meilaopo** [comment]
> 你有设置成continue状态吗？

我调用的sync_local_diff()  传入的outdifffile和continuefile是同一个文件，前者streamoutput，后者streaminput。 streamouput打开时就清空了

**Comment by sisong** [comment]
我实际用命令行程序`hsync_demo`测试过，连续按上述的3次调用，没有发现问题。    
你自己调用的`sync_local_diff`的流参数，可以借鉴函数`sync_local_patch_file2file`对continue的处理逻辑`_open_continue_out`函数，   
重点在于对于输入输出为同一个文件时，输出流打开时要用 `hpatch_TFileStreamOutput_reopen` 。

**Comment by meilaopo** [comment]
> 我实际用命令行程序`hsync_demo`测试过，连续按上述的3次调用，没有发现问题。 你自己调用的`sync_local_diff`的流参数，可以借鉴函数`sync_local_patch_file2file`对continue的处理逻辑`_open_continue_out`函数， 重点在于对于输入输出为同一个文件时，输出流打开时要用 `hpatch_TFileStreamOutput_reopen` 。
> 
> “没有完全支持自定义stream” 既然是自定义流，你当然需要而且必须自己实现reopen流的语意。

命令行怎么测试，我用 hsync_demo OldData  NewDataIndex -diffi#diff 获取下载大小
然后 下载 hsync_demo -cdl  OldData  NewDataIndex NewData -diff#diff 
会提示文件已经存在

**Comment by sisong** [comment]
注意readme的对命令行的说明： 可以用-f
