### ISSUE TITLE
我在改写 hsynz_make.cpp时，遇到了问题，create_sync_files_for_dir方法里面 jni 报错了，咨讯下要怎么改，谢谢

### ISSUE THREAD

**Issue by haohz1987** [sisong/hsynz#31]
报错信息
././hsynzmake.cpp:195:43: error: expected class name
    struct DirPathIgnoreListener : public CDirPathIgnore, IDirPathIgnore
    
././hsynzmake.cpp:198:15: error: member initializer 'CDirPathIgnore' does not name a non-static data member or base class
            : CDirPathIgnore(ignorePathList, isPrintIgnore) {}
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
././hsynzmake.cpp:202:20: error: use of undeclared identifier 'CDirPathIgnore'
            return CDirPathIgnore::isNeedIgnore(path, rootPathNameLen);
            
源码：

    JNIEXPORT jint
    Java_com_github_sisong_hsynzmake_generatePrecisResult(JNIEnv *jenv, jobject jobj, jstring apkFile, jstring hsyniFile, jint matchBlockSize)
    {
        hpatch_BOOL isForceOverwrite = hpatch_FALSE;
        hpatch_BOOL isOutputHelp = hpatch_FALSE;
        hpatch_BOOL isOutputVersion = hpatch_FALSE;

        THSyncMakeSets makeSets;
        makeSets.kSyncBlockSize = (uint32_t)matchBlockSize;
        makeSets.kSafeHashClashBit = 24;
        makeSets.threadNum = 4; //(1<<8)

        hsync_TDictCompress *compressPlugin = 0;
        hpatch_TChecksum *strongChecksumPlugin = &xxh128ChecksumPlugin;
        hsync_THsynz *hsynzPlugin = 0;

        std::vector<std::string> ignoreNewPathList;

        // 最大打开文件数，only used in newDataPath is dir 16 - 64
        size_t kMaxOpenFileNumber = 64; // kMaxOpenFileNumber_default_diff; //(16<<64)

        const char *newDataPath = jenv->GetStringUTFChars(apkFile, NULL);      // apkFile;
        const char *out_hsyni_file = jenv->GetStringUTFChars(hsyniFile, NULL); // .hsyni
        const char *out_hsynz_file = jenv->GetStringUTFChars(hsyniFile, NULL); // .hsynz

        if (!isForceOverwrite)
        {
            hpatch_TPathType outFileType;
            _return_check(hpatch_getPathStat(out_hsyni_file, &outFileType, 0),
                          SYNC_MAKE_CANNOT_OVERWRITE_ERROR, "get %s type", "out_hsyni_file");
            _return_check(outFileType == kPathType_notExist,
                          SYNC_MAKE_CANNOT_OVERWRITE_ERROR, "%s already exists, overwrite", "out_hsyni_file");
            if (out_hsynz_file)
            {
                _return_check(hpatch_getPathStat(out_hsynz_file, &outFileType, 0),
                              SYNC_MAKE_CANNOT_OVERWRITE_ERROR, "get %s type", "out_hsynz_file");
                _return_check(outFileType == kPathType_notExist,
                              SYNC_MAKE_CANNOT_OVERWRITE_ERROR, "%s already exists, overwrite", "out_hsynz_file");
            }
        }

        hpatch_TPathType newType;
        _return_check(hpatch_getPathStat(newDataPath, &newType, 0),
                      SYNC_MAKE_NEWPATH_ERROR, "get %s type", "newDataPath");
        _return_check((newType != kPathType_notExist),
                      SYNC_MAKE_NEWPATH_ERROR, "%s not exist", "newDataPath");
#if (_IS_NEED_DIR_DIFF_PATCH)
        hpatch_BOOL isUseDirSyncUpdate = (kPathType_dir == newType);
        if (isUseDirSyncUpdate)
            _options_check(out_hsynz_file != 0, "used DirSyncUpdate need out_hsynz_file");
#else
    hpatch_BOOL isUseDirSyncUpdate = false;
    _return_check(kPathType_dir != newType,
                  SYNC_MAKE_NEWPATH_ERROR, "%s must file", "newDataPath");
#endif

#if ((defined _CompressPlugin_zlib) || (defined _CompressPlugin_ldef))
        hsync_THsynz_gzip _hsynzPlugin_gzip;
        if (compressPlugin && (0 == strcmp(compressPlugin->compressType(), k_gzip_dictCompressType)))
        {
            _options_check(!isUseDirSyncUpdate, "gzip compress plugin not support DirSyncUpdate");
            hsynzPlugin = &_hsynzPlugin_gzip;
            printf("out_hsynz_file is .gz file format.\n");
        }
#endif

        if ((compressPlugin == 0) && (kPathType_file == newType))
            printf("NOTE: out_hsynz_file's data is same as newDataPath file!\n\n");

        if (makeSets.threadNum > 1)
            printf("muti-thread parallel: opened, threadNum: %d\n", (uint32_t)makeSets.threadNum);

        printf("create%s_sync_data run with strongChecksum plugin: \"%s\"\n",
               isUseDirSyncUpdate ? "_dir" : "", strongChecksumPlugin->checksumType());
        if (compressPlugin)
        {
            printf("create%s_sync_data run with compress plugin: \"%s\"\n",
                   isUseDirSyncUpdate ? "_dir" : "", compressPlugin->compressTypeForDisplay ? compressPlugin->compressTypeForDisplay() : compressPlugin->compressType());
        }
        double time0 = clock_s();
        int result;
        // #if (_IS_NEED_DIR_DIFF_PATCH)
        //         if (isUseDirSyncUpdate)
        result = create_sync_files_for_dir(newDataPath, out_hsyni_file, out_hsynz_file, kMaxOpenFileNumber,
                                           strongChecksumPlugin, compressPlugin, hsynzPlugin, ignoreNewPathList,
                                           makeSets);
        //         else
        // #endif
          // result = create_sync_files_for_file(newDataPath, out_hsyni_file, out_hsynz_file, strongChecksumPlugin,
        //    

        double time1 = clock_s();
        if (result == SYNC_MAKE_SUCCESS)
        {
            _return_check(printFileInfo(out_hsyni_file, "out .hsyni"),
                          SYNC_MAKE_OUTFILE_ERROR, "run printFileInfo(%s,)", out_hsyni_file);
            if (out_hsynz_file)
            {
                _return_check(printFileInfo(out_hsynz_file, "out .hsynz"),
                              SYNC_MAKE_OUTFILE_ERROR, "run printFileInfo(%s,)", out_hsynz_file);
            }
        }
        printf("\ncreate%s_sync_data time: %.3f s\n", isUseDirSyncUpdate ? "_dir" : "", (time1 - time0));
        if (result == SYNC_MAKE_SUCCESS)
            printf("run ok.\n");
        else
            printf("\nERROR!\n\n");
        return result;
    }

**Comment by sisong** [comment]
1. 看起来报的是一个C++类成员初始化语法错误；
2. 我怀疑可能是一个编译器bug，但我试着用 NDK r16b 的 gcc 和 llvm 编译这个类都没有遇到问题；
3. 你可以考虑修改代码绕过这个问题；这个只类负责在遍历文件的时候，按照自己设置的通配符参数过滤掉一些文件。如果不需要过滤，可以考虑修改为： 
```
struct DirPathIgnoreListener:public IDirPathIgnore{
    DirPathIgnoreListener(const std::vector<std::string>& ignorePathList,bool isPrintIgnore=true){}
    //IDirPathIgnore
    virtual bool isNeedIgnore(const std::string& path,size_t rootPathNameLen){
        return false; //也可以自己实现需要忽略哪些文件的逻辑
    }
};
```

**Comment by haohz1987** [comment]
struct DirPathIgnoreListener : public CDirPathIgnore, IDirPathIgnore
 struct DirSyncListener : public IDirSyncListener
 JNI 主要集中在这两个部分的报错，如果我要转成extern "C" ，这两个要怎么改造呢？

**Comment by haohz1987** [comment]
close
