### ISSUE TITLE
Android download Java demo

### ISSUE THREAD

**Issue by sisong** [sisong/hsynz#7]
download rangers of .hsynz file
   
(now, there has compiled Android .so libs, and has its Java API code.)

**Comment by sisong** [comment]
没有完整demo，但有编译好的安卓so库和其Java代码，而且已经有重要产品对外正式发布上线。

**Comment by Thur4day** [comment]
请教一下，Usage C: sync_patch(oldFile,hsyniFile,hsynzDownloader,diffInfoCacheFile,outNewFile,...)这种方式是使用native库的下载方式吗？

**Comment by Thur4day** [comment]
如果我想客户端自己下载差分文件，是用sync_info(oldFile,hsyniFile,hsynzDownloader,diffInfoCacheFile,...)方式获取到差分的信息，然后通过hsynzDownloader的回调去按需下载数据块到diffInfoCacheFile里面吗？diffInfoCacheFile就是readMe里面的-diffi#cacheTempFile文件吗？

**Comment by sisong** [comment]
安卓客户端所有同步函数都调用了native层的hsynz.doSyncPatch函数，根据参数的不同完成不同的阶段任务；   
但这个函数并不负责具体的下载，而是通过回调`IRangeDownloader hsynzDownloader`接口来完成。   
   
hsynz.sync_info函数是只负责执行diff算法(计算出需要下载哪些块，但不下载)，并把该计算结果保存到diffInfoCacheFile文件。（该文件就是readme里面的-diffi#cacheTempFile文件）   
想先下载到差分文件，那就是`Usage A`的方式：先调用hsynz.diff函数，它执行diff算法并同时下载补丁包到outDiffFile文件，然后调用hsynz.patch函数得到outNewFile。

**Comment by Thur4day** [comment]
run throw errorCode: 37
请教一下，哪里能看到errorCode对应的错误信息

**Comment by Thur4day** [comment]
> 安卓客户端所有同步函数都调用了native层的hsynz.doSyncPatch函数，根据参数的不同完成不同的阶段任务； 但这个函数并不负责具体的下载，而是通过回调`IRangeDownloader hsynzDownloader`接口来完成。
> 
> hsynz.sync_info函数是只负责执行diff算法(计算出需要下载哪些块，但不下载)，并把该计算结果保存到diffInfoCacheFile文件。（该文件就是readme里面的-diffi#cacheTempFile文件） 想先下载到差分文件，那就是`Usage A`的方式：先调用hsynz.diff函数，它执行diff算法并同时下载补丁包到outDiffFile文件，然后调用hsynz.patch函数得到outNewFile。

请问下载到outDiffFile文件里需要我在实现的hsynzDownloader方法里通过网络直接写入outDiffFile里吗？还是把responseBody流通过hsynzDownloader的readDownloadedData方法传到native层，native自己写入文件？

**Comment by sisong** [comment]
native自己写入diffFile文件

**Comment by Thur4day** [comment]
class HsynzDownloader(val scope: CoroutineScope) : hsynz.IRangeDownloader {
        val apkUrl by lazy {
            "https://xxx.85a7ece1e135233231cc7de4504a525a.zip"
        }

        val okHttpClient by lazy {
            OkHttpClient.Builder().build()
        }

        var needLoadRanges: hsynz.TNeedDownloadRanges? = null


        var dstBufferPos = 0

        override fun onSyncInfo(newFileSize: Long, hsynzFileSize: Long, hsynzDiffSize: Long) {
            Log.e(
                "hsynz",
                "onSyncInfo: newFileSize=$newFileSize, hsynzFileSize=$hsynzFileSize, hsynzDiffSize=$hsynzDiffSize"
            )
        }

        override fun downloadRanges(needRanges: hsynz.TNeedDownloadRanges?): Boolean {
            Log.e(
                "hsynz",
                "downloadRanges: sumRangeCount=${needRanges?.sumRangeCount} sumDataLen=${needRanges?.sumDataLen}"
            )
            Log.e("hsynz", Thread.currentThread().name)

            if (needRanges == null) {
                return false
            }
            needLoadRanges = needRanges
            return true
        }

        override fun readDownloadedData(dstBuf: hsynz.TByteBuf?, readDataLen: Int): Boolean {
            Log.e("hsynz", "readDownloadedData: dstBuf=$dstBuf, readDataLen=$readDataLen")
            needLoadRanges?.let {
                //            scope.launch(Dispatchers.IO) {
                for (i in 0 until it.sumRangeCount) {
                    val ranges = longArrayOf(0, 0)
                    Log.e(
                        "hsynz",
                        "downloadRanges: ${it.getNextRanges_MTSafe(ranges)} index=$i ranges=${ranges[0]}-${ranges[1]}"
                    )
                    val range = Pair(ranges[0], ranges[1])
                    val result = requestRanges(dstBuf, apkUrl, range, okHttpClient)
                    if (!result) {
                        return false
                    }
//                }
                }
            }

            return true
        }

        private fun requestRanges(
            dstBuf: hsynz.TByteBuf?,
            url: String,
            range: Pair<Long, Long>,
            okHttpClient: OkHttpClient
        ): Boolean {
//            withContext(Dispatchers.IO) {
            runCatching {
                val request = Request.Builder()
                    .url(url)
                    .addHeader("Range", "bytes=${range.first}-${range.second}")
                    .build()
                val response = okHttpClient.newCall(request).execute()
                if (response.isSuccessful) {
                    val body = response.body
                    body?.byteStream()?.use { input ->
                        val buffer = ByteArray(4096)
                        var len = 0
                        while (input.read(buffer).also { len = it } != -1) {
                            if (len > 0) {
                                dstBuf?.let {
                                    Log.e("hsynz", "requestRanges read response.body: len=$len")
                                    it.setData(dstBufferPos, buffer, 0, len)
                                    dstBufferPos += len
                                }
                            }
                        }
                    }
                }
                return true

//                }
            }.getOrElse { e ->
                Log.e("hsynz", "requestRanges IOException: ${e.message}")
            }
            return false
        }
    }

我目前demo的IRangeDownloader实现是这样，但是这样调用diffFile并没有数据.
想请教一下readDownloadedData()方法和hsynz.TByteBuf.serData()方法的正确调用方式是怎么样的？

**Comment by sisong** [comment]
@Thur4day 
需要在每次进入readDownloadedData时，设置dstBufferPos=0;  因为dstBuf缓冲区只是一个固定大小的bytes数组，用于中转数据的。    
"xxx.85a7ece1e135233231cc7de4504a525a.zip" 为什么是zip文件，按hsyz项目的命名，应该是个.hsynz文件，不会是个zip文件（该文件不压缩时就是指原文件，而用-gzip参数式时就是.gz格式的文件）。   
建议可以用一个本地文件来测试，整个流程调通以后在转成http下载。   
   
另外可以考虑的优化：http1.1请求支持一次请求多个区域（ranges），这样可以大量减少请求次数，即 "Range: bytes=" 后面跟多个下载的区域。   而且还可以考虑在downloadRanges的时候就启动异步线程负责快速下载。

**Comment by Thur4day** [comment]
> @Thur4day 需要在每次进入readDownloadedData时，设置dstBufferPos=0; 因为dstBuf缓冲区只是一个固定大小的bytes数组，用于中转数据的，每次必须按顺序填满需要的数据长度。 "xxx.85a7ece1e135233231cc7de4504a525a.zip" 为什么是zip文件，按hsyz项目的命名，应该是个.hsynz文件，不会是个zip文件（该文件不压缩时就是指原文件，而用-gzip参数式时就是.gz格式的文件）。 建议可以用一个本地文件来测试，整个流程调通以后在转成http下载。
> 
> 另外可以考虑的优化：http1.1请求支持一次请求多个区域（ranges），这样可以大量减少请求次数，即 "Range: bytes=" 后面跟多个下载的区域。 而且还可以考虑在downloadRanges的时候就启动异步线程负责快速下载。

我使用本地文件测试调通了。url对应的.zip文件就是我的原文件，因为没有设置压缩参数和out_hsynz_file，所以没有生成额外的.hsynz文件。
在downloadRanges的时候启动下载这里我尝试了，这里下载下来我保存的是responseBody，因为之前你说是native自己负责写文件。那么我在每次进入readDownloadedData时，dstBufferPos重置为0，然后调用dstBuf.setData(dstBufferPos, buffer, 0, len)。是这样吗？

**Comment by Thur4day** [comment]
> @Thur4day 需要在每次进入readDownloadedData时，设置dstBufferPos=0; 因为dstBuf缓冲区只是一个固定大小的bytes数组，用于中转数据的，每次必须按顺序填满需要的数据长度。 "xxx.85a7ece1e135233231cc7de4504a525a.zip" 为什么是zip文件，按hsyz项目的命名，应该是个.hsynz文件，不会是个zip文件（该文件不压缩时就是指原文件，而用-gzip参数式时就是.gz格式的文件）。 建议可以用一个本地文件来测试，整个流程调通以后在转成http下载。
> 
> 另外可以考虑的优化：http1.1请求支持一次请求多个区域（ranges），这样可以大量减少请求次数，即 "Range: bytes=" 后面跟多个下载的区域。 而且还可以考虑在downloadRanges的时候就启动异步线程负责快速下载。

非常感谢，还得请教：
readDownloadedData这个方法是回调一次还是说我按顺序填满需要的数据长度后，return true。然后会再次进入这个方法？readDownloadedData的循环调用是native层控制的是吗？没有数据填充的时候等待要客户端来做？相当于我在downloadRanges的时候就启动异步线程负责快速下载这里是生产者，readDownloadedData是消费者？我需要控制流的生产和消费即可？

**Comment by sisong** [comment]
@Thur4day    想法没有什么问题。

**Comment by sisong** [comment]
@Thur4day
可以看到返回值类型为 TSyncClient_resultType ，然后查看定义就能知道 42 为 kSyncClient_checksumSyncDataError，  这表示同步到的数据强校验失败（提供的数据不对）；   
如果看不出定义的意义，建议搜索错误码，看用在什么地方。

**Comment by sisong** [comment]
移动端默认没有打开目录支持   
     需要调用hsync_patch_2dir()来完成。   
（另外也可以调用checkNewSyncInfoType_by_file()通过.hsyni文件获知相关信息）   
 `#define  _IS_NEED_DIR_DIFF_PATCH    0`和 `-D_IS_NEED_DIR_DIFF_PATCH=0 `  修改0为1   
`HDiffPatch\dirDiffPatch\dir_patch` 目录中的.c文件都需要包含；还有 `HDiffPatch/dirDiffPatch/dir_diff/dir_manifest.cpp` 和 `dir_sync_client.cpp`

**Comment by Thur4day** [comment]
@sisong 提供一个我这边调试通了的demo代码：
`object hsynzDownloader : hsynz.IRangeDownloader {

        private const val BLOCK_SIZE = 2048

        private val url by lazy {
            "https://xxx_your_remote_hsynz_file.hsynz"
        }

        private val okHttpClient by lazy {
            OkHttpClient.Builder().build()
        }

        private var readBufferPos = 0L

        private var readPosCache = 0L

        private var readEnd = false

        private var error = false

        private var sumDataLen = 0L

        private val blockingDeque = LinkedBlockingDeque<ByteArray>(8)

        private val outputStream = ByteArrayOutputStream(BLOCK_SIZE)

        override fun onSyncInfo(newFileSize: Long, hsynzFileSize: Long, hsynzDiffSize: Long) {
            Log.e(
                "hsynz time",
                "onSyncInfo: newFileSize=$newFileSize, hsynzFileSize=$hsynzFileSize, hsynzDiffSize=$hsynzDiffSize"
            )
        }

        override fun downloadRanges(needRanges: hsynz.TNeedDownloadRanges?): Boolean {
            Log.e(
                "hsynz time",
                "downloadRanges: sumRangeCount=${needRanges?.sumRangeCount} sumDataLen=${needRanges?.sumDataLen}"
            )
            sumDataLen = needRanges?.sumDataLen ?: 0
            Log.e("hsynz", Thread.currentThread().name)

            if (needRanges == null) {
                return false
            }
            Thread {
                for (i in 0 until needRanges.sumRangeCount) {
                    val ranges = longArrayOf(0, 0)
                    Log.e(
                        "hsynz",
                        "downloadRanges: ${needRanges.getNextRanges_MTSafe(ranges)} index=$i ranges=${ranges[0]}-${ranges[1]}"
                    )
                    // range分段很多的时候一个请求会返回200，返回原始包
                    // 这里每个分段做一次请求，后续可优化为3-5个分段合并一次请求
                    val range = Pair(ranges[0], ranges[1])
                    val rangesStr = "${range.first}-${range.second}"
                    val result = requestRanges(url, rangesStr, okHttpClient)
                    if (!result) {
                        Log.e("hsynz", "downloadRanges: requestRanges failed")
                    }
                }
            }.start()

            return true
        }

        override fun readDownloadedData(dstBuf: hsynz.TByteBuf?, readDataLen: Int): Boolean {
            Log.e("hsynz", "readDownloadedData: dstBuf=$dstBuf, readDataLen=$readDataLen")
            while (true) {
                if (error) {
                    return false
                }
                val data = blockingDeque.take()
                dstBuf?.setData(0, data, 0, readDataLen)
                readPosCache += readDataLen
                Log.e("hsynz", "readDownloadedData: readPosCache=$readPosCache")
                return true
            }
        }

        private fun requestRanges(
            url: String,
            range: String,
            okHttpClient: OkHttpClient
        ): Boolean {
            runCatching {
                val request = Request.Builder()
                    .url(url)
                    .method("GET", null)
                    .addHeader("Range", "bytes=$range")
                    .build()
                val response = okHttpClient.newCall(request).execute()
                Log.e("hsynz", "requestRanges: response=${request.headers}")
                Log.e("hsynz", "requestRanges: response code=${response.code}")
                if (response.isSuccessful) {
                    val body = response.body
                    if (body != null) {
                        body.byteStream().use { input ->
                            while (true) {
                                val buffer = ByteArray(BLOCK_SIZE)
                                var readCount = outputStream.size()
                                var end = false
                                while (readCount < BLOCK_SIZE) {
                                    val len = input.read(buffer, readCount, BLOCK_SIZE - readCount)
                                    if (len == -1) {
                                        end = true
                                        Log.e("hsynz", "requestRanges end: readCount=$readCount")
                                        break
                                    } else {
                                        readCount += len
                                    }
                                }
                                outputStream.write(buffer, 0, readCount)
                                val size = outputStream.size()
                                if (size == BLOCK_SIZE) {
                                    blockingDeque.put(outputStream.toByteArray())
                                    outputStream.reset()
                                }
                                readBufferPos += readCount
//                                Log.e("hsynz", "requestRanges: read block $readCount")
//
                                if (end) {
                                    Log.e(
                                        "hsynz",
                                        "requestRanges end: outputStream=${outputStream.size()}"
                                    )
                                    // 最后一段数据
                                    if (outputStream.size() > 0) {
                                        blockingDeque.put(outputStream.toByteArray())
                                        outputStream.reset()
                                    }
                                    Log.e(
                                        "hsynz",
                                        "requestRanges read response.body: dstBufferPos=$readBufferPos"
                                    )
                                    break
                                }
                            }
                        }
                    } else {
                        error = true
                        Log.e("hsynz", "requestRanges: response.body is null")
                    }
                    readEnd = true
                } else {
                    error = true
                    return false
                }
                return true
            }.getOrElse { e ->
                Log.e("hsynz", "requestRanges IOException: ${e.message}")
            }
            error = true
            return false
        }
    }`
比较简陋，感谢解答我的问题。

**Comment by Thur4day** [comment]
@sisong 我这里有一个比较简陋的实现，调通了正常的差分流程。感谢回到我的疑问。
```
object hsynzDownloader : hsynz.IRangeDownloader {

        private const val BLOCK_SIZE = 2048

        private val url by lazy {
            "https://xxx_your_remote_file.hsynz"
        }

        private val okHttpClient by lazy {
            OkHttpClient.Builder().build()
        }

        private var readBufferPos = 0L

        private var readPosCache = 0L

        private var readEnd = false

        private var error = false

        private var sumDataLen = 0L

        private val blockingDeque = LinkedBlockingDeque<ByteArray>(8)

        private val outputStream = ByteArrayOutputStream(BLOCK_SIZE)

        override fun onSyncInfo(newFileSize: Long, hsynzFileSize: Long, hsynzDiffSize: Long) {
            Log.e(
                "hsynz time",
                "onSyncInfo: newFileSize=$newFileSize, hsynzFileSize=$hsynzFileSize, hsynzDiffSize=$hsynzDiffSize"
            )
        }

        override fun downloadRanges(needRanges: hsynz.TNeedDownloadRanges?): Boolean {
            Log.e(
                "hsynz time",
                "downloadRanges: sumRangeCount=${needRanges?.sumRangeCount} sumDataLen=${needRanges?.sumDataLen}"
            )
            sumDataLen = needRanges?.sumDataLen ?: 0
            Log.e("hsynz", Thread.currentThread().name)

            if (needRanges == null) {
                return false
            }
            Thread {
                for (i in 0 until needRanges.sumRangeCount) {
                    val ranges = longArrayOf(0, 0)
                    Log.e(
                        "hsynz",
                        "downloadRanges: ${needRanges.getNextRanges_MTSafe(ranges)} index=$i ranges=${ranges[0]}-${ranges[1]}"
                    )
                    // range分段很多的时候一个请求会返回200，返回原始包
                    // 这里每个分段做一次请求，后续可优化为3-5个分段合并一次请求
                    val range = Pair(ranges[0], ranges[1])
                    val rangesStr = "${range.first}-${range.second}"
                    val result = requestRanges(url, rangesStr, okHttpClient)
                    if (!result) {
                        Log.e("hsynz", "downloadRanges: requestRanges failed")
                    }
                }
            }.start()

            return true
        }

        override fun readDownloadedData(dstBuf: hsynz.TByteBuf?, readDataLen: Int): Boolean {
            Log.e("hsynz", "readDownloadedData: dstBuf=$dstBuf, readDataLen=$readDataLen")
            while (true) {
                if (error) {
                    return false
                }
                val data = blockingDeque.take()
                dstBuf?.setData(0, data, 0, readDataLen)
                readPosCache += readDataLen
                Log.e("hsynz", "readDownloadedData: readPosCache=$readPosCache")
                return true
            }
        }

        private fun requestRanges(
            url: String,
            range: String,
            okHttpClient: OkHttpClient
        ): Boolean {
            runCatching {
                val request = Request.Builder()
                    .url(url)
                    .method("GET", null)
                    .addHeader("Range", "bytes=$range")
                    .build()
                val response = okHttpClient.newCall(request).execute()
                Log.e("hsynz", "requestRanges: response=${request.headers}")
                Log.e("hsynz", "requestRanges: response code=${response.code}")
                if (response.isSuccessful) {
                    val body = response.body
                    if (body != null) {
                        body.byteStream().use { input ->
                            while (true) {
                                val buffer = ByteArray(BLOCK_SIZE)
                                var readCount = outputStream.size()
                                var end = false
                                while (readCount < BLOCK_SIZE) {
                                    val len = input.read(buffer, readCount, BLOCK_SIZE - readCount)
                                    if (len == -1) {
                                        end = true
                                        Log.e("hsynz", "requestRanges end: readCount=$readCount")
                                        break
                                    } else {
                                        readCount += len
                                    }
                                }
                                outputStream.write(buffer, 0, readCount)
                                val size = outputStream.size()
                                if (size == BLOCK_SIZE) {
                                    blockingDeque.put(outputStream.toByteArray())
                                    outputStream.reset()
                                }
                                readBufferPos += readCount
//                                Log.e("hsynz", "requestRanges: read block $readCount")
//
                                if (end) {
                                    Log.e(
                                        "hsynz",
                                        "requestRanges end: outputStream=${outputStream.size()}"
                                    )
                                    // 最后一段数据
                                    if (outputStream.size() > 0) {
                                        blockingDeque.put(outputStream.toByteArray())
                                        outputStream.reset()
                                    }
                                    Log.e(
                                        "hsynz",
                                        "requestRanges read response.body: dstBufferPos=$readBufferPos"
                                    )
                                    break
                                }
                            }
                        }
                    } else {
                        error = true
                        Log.e("hsynz", "requestRanges: response.body is null")
                    }
                    readEnd = true
                } else {
                    error = true
                    return false
                }
                return true
            }.getOrElse { e ->
                Log.e("hsynz", "requestRanges IOException: ${e.message}")
            }
            error = true
            return false
        }
    }
```

**Comment by sisong** [comment]
`后续可优化为3-5个分段合并一次请求`   
16或32应该都可以

**Comment by Thur4day** [comment]
@sisong 之前CDN不支持多range块。目前换了一个支持的，但是我多range块下载后，在流中过滤掉boundary信息后，再读取一个blockSize的数据传输到readDownloadedData后就校验不通过了，对比和单range的数据，一个blockSize的数据比之前小了不少。不知道因为什么。

**Comment by sisong** [comment]
这个问题明显和hsynz库没有关系了，所以可以猜测是`过滤掉boundary信息` 的实现有bug；你可以打印多区域数据和单区域下载的数据的差别就能更清晰了。

**Comment by Thur4day** [comment]
> 这个问题明显和hsynz库没有关系了，所以可以猜测是`过滤掉boundary信息` 的实现有bug；你可以打印多区域数据和单区域下载的数据的差别就能更清晰了。

是的，我是这样打印对比的。

**Comment by Thur4day** [comment]
@sisong 想确认一下，目前的算法里面多range下载的情况下，是否需要客户端来过滤掉boundary信息？类似这种：
--00000000000004501031
Content-Type: binary/octet-stream
Content-Range: bytes 0-13529087/18235752

附带这些信息的话，数据校验就会失败是吗？

**Comment by sisong** [comment]
是的
