### ISSUE TITLE
How do i use it on windows?

### ISSUE THREAD

**Issue by dungeon2567** [sisong/hsynz#9]

**Comment by sisong** [comment]
you can download cmdline [hsynz_v0.9.1_bin_windows64.zip](https://github.com/sisong/hsynz/releases/download/v0.9.1/hsynz_v0.9.1_bin_windows64.zip)  from  https://github.com/sisong/hsynz/releases      
   
or used VC build `hsynz\builds\vc\hsynz.sln` by youself.

**Comment by dungeon2567** [comment]
I have downloaded it and the hsync_make is working fine but hsync_http always give http error

**Comment by sisong** [comment]
you can used hsync_demo for test full process.        
   
for hsync_http download error:     
1. error when downloading **.hsyni** or **.hsynz**?
2. http(s) server support HTTP/1.1 muti-ranges?
3. http(s) server URL is public?   ( I want test it. )

**Comment by dungeon2567** [comment]
Error on hsynz (both, but i have hsyni locally).


this is the url:

https://launcher.golden-helmet.tk/out.hsynz

**Comment by sisong** [comment]
now, not support oldPath outNewPath same path.      

Because I haven't figured out how to deal with this situation clearly.       
The most critical problem: it is not possible to safely and securely delete files in oldDir that are not in newDir.

**Comment by sisong** [comment]
I run `$hsync_http -dl#https://launcher.golden-helmet.tk/out.hsynz -f out.hsynz.tmp`  ，got error log:
```
TcpSocket::open(): SSL requested...
SSL handshake now...
open_ssl: ssl_handshake returned -0x7780

TcpSocket::close
HttpSocket::_FinishRequest
```
mbedtls SSL has reported an error...

**Comment by sisong** [comment]
I run `$hsync_http -dl#https://launcher.golden-helmet.tk/out.hsynz -f out.hsynz.tmp`  ，got error log:
```
TcpSocket::open(): SSL requested...
SSL handshake now...
open_ssl: ssl_handshake returned -0x7780

TcpSocket::close
HttpSocket::_FinishRequest
```
mbedtls SSL has reported an error...

**Comment by dungeon2567** [comment]
It is using cloudflare with cloudflare certificate. I think they are secure.

Maybe mbedtls is broken

**Comment by sisong** [comment]
I search the error code , got:
MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE               -0x7780  /**< A fatal alert message was received from our peer. */

**Comment by sisong** [comment]
I fixed -0x7780:  add mbedtls_ssl_set_hostname() when init SSL;    
`$hsync_http -dl#https://launcher.golden-helmet.tk/out.hsynz -f out.hsynz.tmp`  download ok;      
code at [dev](https://github.com/sisong/hsynz/tree/dev) branch.   
   
I test download with single range Request, it's ok;  but when download with two ranges Request, it's fail.

**Comment by sisong** [comment]
I used curl test the URL:   
`$curl https://launcher.golden-helmet.tk/out.hsynz -i`   
run ok   
`$curl https://launcher.golden-helmet.tk/out.hsynz -i -H "Range: bytes=0-1023"`   
run ok   
`$curl https://launcher.golden-helmet.tk/out.hsynz -i -H "Range: bytes=0-50,100-150"`   
400 Bad Request

**Comment by sisong** [comment]
next version will support this server(only support single-range, not muti-ranges);     
cmdline will add "-r-1" for this.
